# Build stage
FROM python:3.11-slim as builder
WORKDIR /app
COPY ../applications/python-app/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Final stage
FROM gcr.io/distroless/python3:nonroot
WORKDIR /app
COPY --from=builder /usr/local/lib/python3.11/site-packages /usr/local/lib/python3.11/site-packages
COPY ../applications/python-app/ .
USER nonroot:nonroot
CMD ["app.py"]