# Build stage
FROM golang:1.21 as builder
WORKDIR /app
COPY ../applications/go-app/ .
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o main .

# Final stage
FROM alpine:3.18
WORKDIR /
COPY --from=builder /app/main /
RUN apk --no-cache add ca-certificates
ENTRYPOINT ["/main"]