apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-distroless
  labels:
    app: go-distroless
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-distroless
  template:
    metadata:
      labels:
        app: go-distroless
    spec:
      containers:
      - name: go-distroless
        image: ${REGISTRY_URL}/go-distroless:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: go-distroless
spec:
  selector:
    app: go-distroless
  ports:
  - port: 80
    targetPort: 8080
  type: ClusterIP