apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-alpine
  labels:
    app: nodejs-alpine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-alpine
  template:
    metadata:
      labels:
        app: nodejs-alpine
    spec:
      containers:
      - name: nodejs-alpine
        image: ${REGISTRY_URL}/node-alpine:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-alpine
spec:
  selector:
    app: nodejs-alpine
  ports:
  - port: 80
    targetPort: 8080
  type: ClusterIP